### ISSUE TITLE
(Error feedback) When you download Cr4shed and restart device, it will prevent Cydia from loading data and loading the package list.

### ISSUE THREAD

**Issue by villager1314** [pwned4ever/Th0r_Freya#32] opened 2023-02-04 06:14 UTC
After uninstalling Cr4shed with Sileo, Cydia returned to normal operation.

**Comment by villager1314** [comment] 2023-02-04 06:20
Crashreporter doesn't work because it gives the cause of the accident that does not match the application and dependency I downloaded.

**Comment by pwned4ever** [comment] 2023-02-04 21:16
Do you have Twitter?

Sent from my iPhone

On Feb 4, 2023, at 1:20 AM, villager1314 ***@***.***> wrote:

﻿

Crashreporter doesn't work because it gives the cause of the accident that does not match the application and dependency I downloaded.

**Comment by villager1314** [comment] 2023-02-05 00:58
no😭😭🙈🙈

**Comment by villager1314** [comment] 2023-02-05 01:01
Is your Twitter account pwned4⃣️ever?

**Comment by villager1314** [comment] 2023-02-05 01:02
If so, I will pay attention to the latest developments.

**Comment by pwned4ever** [comment] 2023-02-07 02:51
issued resolved in 1.3.6 afaik

**Closed by pwned4ever** 2023-02-07 02:51 UTC
