### ISSUE TITLE
install Reveal2Loader do not work....

### ISSUE THREAD

**Issue by mdreamfly** [pwned4ever/Th0r_Freya#30] opened 2023-01-29 06:27 UTC
Hello I install Reveal2Loader via Cydia,  install success , but in Setting no entry about Reveal...

device info:
iphone 6 plus 
ios 12.5.6
freya 1.3.2

**Comment by pwned4ever** [comment] 2023-01-29 10:29
honestly I think I broke something in 1.3.2, I just hopefully fixed with 1.3.3, please remove the jb and start fresh with 1.3.3 for the last time I hope. let me know if the issue is resolved after using the update 1.3.3

**Comment by mdreamfly** [comment] 2023-01-31 10:53
thx for reply , i test in 1.3.4 it's resolved. nice job!

**Comment by pwned4ever** [comment] 2023-02-01 06:58
that's great, hope 1.3.5 is the same with minor fixes again chimera removing and some...

**Closed by pwned4ever** 2023-02-01 06:58 UTC
