### ISSUE TITLE
package manager missing at home

### ISSUE THREAD

**Issue by Lonelyobserve** [pwned4ever/Th0r_Freya#1] opened 2022-07-21 15:06 UTC
it seems cydia package manager is there but the icon is missing found out that its there when i tried to install sileo it launches cydia but it also does not shows up
ios 12.5.5/ipad mini 2 /freya 1.0

**Comment by pwned4ever** [comment] 2022-07-22 01:44
Does Mterminal show up ?

**Comment by Lonelyobserve** [comment] 2022-07-22 05:14
no new app shows up after jailbreak boot i could confirm that jb is done as i have a fakesigned app which launches and my camera app works which is the reason i switch from chimera

**Comment by pwned4ever** [comment] 2022-07-23 15:49
Very confused what you're describing. Please add all info about how you've added the ipa to your device? What device and iOS version. And if you have another Jb installed and running during the use of freya. Also. Don't build the project yourself. I found issues with incorrectly building the project and trying to run it. Either run it directly through the project and debug it. Or install the ipa and run the app like that. Then verify any issues. The issue you're having seems to be how you're using Freya/installing it

Sent from my iPhone

On Jul 22, 2022, at 1:14 AM, Lonelyobserve ***@***.***> wrote:

﻿

no new app shows up after jailbreak boot i could confirm that jb is done as i have a fakesigned app which launches and my camera app works which is the reason i switch from chimera

**Comment by Lonelyobserve** [comment] 2022-07-24 05:03
sideloaded freya through altstore sideloading, its ios 12.5.5 ,has chimera but reboot and removed through freya, i got ipa from the release folder of this repo

**Comment by pwned4ever** [comment] 2022-07-24 10:48
Ok, so to be clear. Freya worked to remove sileo and chimera Jb files and did the uicache of the icon to remove sileo successfully. But. When using Freya to jailbreak and install cydia. You got nothing? A video of the log would maybe help. Have you tried to remove the Jb and start over again? Using Freya of course. Also has Freya been able to do the snapshot rename? I don't see what the issue is. Since every device I've tested it on works without flaw or errors. Would like to get this issue solved for you. But with the amount of info. It's kinda impossible. Do you have a Mac or any computer at home? A second iPhone to record the process?

Sent from my iPhone

On Jul 24, 2022, at 1:03 AM, Lonelyobserve ***@***.***> wrote:

﻿

sideloaded freya through altstore sideloading, its ios 12.5.5 ,has chimera but reboot and removed through freya, i got ipa from the release folder of this repo

**Comment by Lonelyobserve** [comment] 2022-07-25 13:50
https://drive.google.com/drive/folders/1xCRMxE2Kss2K_UhGJFuxewJUnVE2zt4X?usp=sharing
here i rec from chimera jb to freya jb

**Comment by pwned4ever** [comment] 2022-07-25 15:55
Ok please send me the exact model of the iPad mini so I can get the kernelcache and or amfid from it and find any offsets maybe specific for that iPad. Also I can try to install another uicache and test it. It looks like everything installed without issues. However it seems that uicache succeeded but didn't work as it's supposed to. Since it returned 0 for success. Do you have a Mac? Are you able to build the app through Xcode?

Sent from my iPhone

On Jul 25, 2022, at 9:52 AM, Lonelyobserve ***@***.***> wrote:

﻿

https://drive.google.com/drive/folders/1xCRMxE2Kss2K_UhGJFuxewJUnVE2zt4X?usp=sharing
here i rec from chimera jb to freya jb

**Comment by Lonelyobserve** [comment] 2022-07-25 16:06
ME277HN/A     a1489
I dont have a mac or any knowledge of xcode

**Comment by pwned4ever** [comment] 2022-07-26 10:48
Whenever you get a chance. Remove the Jailbreak and start over again with version 1.0~a. I updated it a few mins ago. Please let me know if it's still the same issue or if cydia appears. Good luck .. here's a direct link to the ipa https://github.com/pwned4ever/Th0r_Freya/blob/main/Releases/Freya.ipa

Sent from my iPhone

On Jul 25, 2022, at 12:06 PM, Lonelyobserve ***@***.***> wrote:

﻿

ME277HN/A a1489
I dont have a mac or any knowledge of xcode

**Comment by Lonelyobserve** [comment] 2022-07-26 18:16
no ,other app shows up tried twice restore root fs and JB, but if i open cydia through browser i could see mterminal installed, alas even other jb are also buggy on a7 so i wont take more of your time.

**Comment by pwned4ever** [comment] 2022-07-26 18:36
It's no bother. I'd like to resolve this issue for maybe others have this exact issue. I have 2-3?other options I'd like to try first before we call it quits. So I'll rebuild it later today hopefully and apply another update for you to test. Please take a bit of time to test these updates, so we can find and resolve the issue. Thank you for the reply and feedback. The next update should work because you used freya to remove the sileo Jailbreak icon and it worked. I will now try in the needy update to use the same way of uicache as I do when doing the restore rootfs.

Sent from my iPhone

On Jul 26, 2022, at 2:16 PM, Lonelyobserve ***@***.***> wrote:

﻿

no ,other app shows up tried twice restore root fs and JB, but if i open cydia through browser i could see mterminal installed, alas even other jb are also buggy on a7 so i wont take more of your time.

**Comment by Lonelyobserve** [comment] 2022-07-26 19:13
surely i can test new build as its a secondary device .

**Comment by pwned4ever** [comment] 2022-07-27 00:05
I've added the change for uicache to resort to the one that is used during the restore roots process. please try version 1.0~b and let me know if it works to show the Cydia icon after jailbreaking and installing Cydia from the first initial jailbreak. of course you will have to remove the jailbreak and start from fresh again to allow the installing of debs and uicache to be run on the first run. otherwise when using freya to enable the jailbreak, uicache will not be run during this process to save time during the jb process. Please let me know as soon as you get a result :)

**Comment by Lonelyobserve** [comment] 2022-07-27 06:07
1.0 b has the some result no app icon appear its same as previous could open cydia through browser( i did a restore rootfs and then install freya)

**Comment by pwned4ever** [comment] 2022-07-29 10:31
Do a restore rootfs first. Then install and run Freya 1.0~c
Even if the Jailbreak fails to show you the cydia icon on first initially use. Reboot and run the enable jailbreak. Uicache will be run again upon jailbreakd loading and apply it to cydia.app only
Best of luck. Have a good day and thanks for testing

Sent from my iPhone

On Jul 27, 2022, at 2:07 AM, Lonelyobserve ***@***.***> wrote:

﻿

1.0 b has the some result no app icon appear its same as previous could open cydia through browser( i did a restore rootfs and then install freya)

**Comment by Lonelyobserve** [comment] 2022-07-29 18:32
well yes thanks ,it worked in the end, the first reboot freeze at boot but force restart (home + power) did boot and cydia and terminal show up and enable freya respring and its working

**Comment by pwned4ever** [comment] 2022-07-29 20:23
Awesome! I am finally able to close this issue. Onto the next issue :)  I'm happy it finally worked :) thank you very much for the vigorous testing.

Sent from my iPhone

On Jul 29, 2022, at 2:32 PM, Lonelyobserve ***@***.***> wrote:

﻿

well yes thanks ,it worked in the end, the first reboot freeze at boot but force restart (home + power) did boot and cydia and terminal show up and enable freya respring and its working

**Comment by pwned4ever** [comment] 2022-07-30 06:57
Issue resolved. Uicache -p option now run on enabling Jb and initial jailbreak

**Comment by pwned4ever** [comment] 2022-07-30 06:59
Fixed uicache and added -p to enabling Jb and initial Jb

**Closed** 2022-09-08 19:37 UTC

**Comment by pwned4ever** [comment] 2022-10-11 07:50
Thank you. I will first try with a different uicache and then try with installing The uikittools deb update which is a third different uicache. iirc. Then if neither of these routes work. I will reverse the amfid and kernelcache from your iPad mini 2nd Gen. And verify the amfid registers didn't change. Hopefully the first uicache fix will do the trick for everything :)

**Comment by pwned4ever** [comment] 2022-10-11 09:10
Also if you have Twitter please send me a video of everything happening and during the process of jailbreaking. With more info I can help solve this issue. Twitter = @shogunpwnd

Sent from my iPhone

On Jul 22, 2022, at 1:14 AM, Lonelyobserve ***@***.***> wrote:

﻿

no new app shows up after jailbreak boot i could confirm that jb is done as i have a fakesigned app which launches and my camera app works which is the reason i switch from chimera
